### PR TITLE
refactor: remove top-level await in cli.mjs

### PR DESCRIPTION
**Pull request by jerome-benoit**

### CODE REVIEW

**Comment by voxpelli** [comment]
I would like a reason for this? Why not use a top level await?

**Comment by jerome-benoit** [comment]
> I would like a reason for this? Why not use a top level await?

It enforces ESM support in the runtime to run the CLI (node.js versions without ESM are still used, despite security issues, no support, ...). 

I will complete changes to make the CLI CJS compliant, like the rest of the code base.

**Comment by jerome-benoit** [comment]
> I will complete the changes to make the CLI CJS compliant, like the rest of the code base.

Because of peowly, which is ESM only, CLI can't be easily converted to CJS. Is peowly strictly needed? I think having a code base consistent and working with CJS (with warnings) and ESM ease adoption.

**Comment by voxpelli** [comment]
ESLint itself does not support anything older than Node.js 18 and so doesn’t Neostandard?

And currently the CLI is just a config helper, not core to the experience?

**Comment by bcomnes** [comment]
Im sympathetic to supporting cjs where appropriate, but the cli isn't imported anywhere and requires a runtime supporting esm so use of TLA shouldn't cause any grief here.

**Comment by jerome-benoit** [comment]
> And currently the CLI is just a config helper, not core to the experience?

It's the very first neostandard component the user deal with at migration. In case he tries it on an a CJS code base running with unsupported node.js, the end result of his first experiment is a failure. 

ESlint and its CLI while not supported on old node version still works on them (use at your own risk).

The workaround is: 

- upgrade temporary to recent node version
- do the migration 
- downgrade the node version

Or

- do the migration by hand ...

Or 

- stick to the standard deps 

And it can be trivially avoided. 

Either a code base support CJS and ESM at a whole, either it only works with ESM. But making a library working with CJS and ESM with an CLI requiring ESM make little sense.

**Comment by voxpelli** [comment]
If it was the CLI for running the tests, then I would add https://github.com/voxpelli/version-guard to ensure it fails silently on old versions

Eg. peowly itself uses [`parseArgs`](https://nodejs.org/api/util.html#utilparseargsconfig) that’s only available in node.js since 16.9.0 / 16.11.0  and top level awaits in esm is supported since 14.8.0, so essentially it would take someone to run something so old that many modern JS and Node API:s are not available there, and that is highly unstable and unsupported, any addition of a modern JS feature will potentially break it, eg something like the highly useable [`structuredClone`](https://nodejs.org/api/globals.html#structuredclonevalue-options) that’s available since 17.0.0

As the creator and maintainer of https://github.com/voxpelli/node-installed-check, which this module uses, I’m very keen on publishing correct engine ranges and on sticking to those ranges, and since ESLint doesn’t support anything older than Node 18, Node.JS doesn’t support anything older than Node 18, then the only thing I would be prepared to change is to do a `version-guard` variant where it exits with a more user friendly error

**Comment by voxpelli** [comment]
Also: It makes little sense to me to avoid using ESM in a CLI since that’s the one place ESM actually gives a distinct advantage, as it permits top level await, making for clean readable code

**Comment by jerome-benoit** [comment]
So, 

- node version check in the cli to display a meaningful message for unsupported version. The way `version-guard` is implementing it not handy: the version check is not based on a unique fine grained source like engines content in package.json and it does not seem to be able to optionally only use it. 
- unneeded slower async primitives to read file replaced by faster sync implementation (for the sake of using primitives with a semantic matching CLI synchronous design)?

**Comment by voxpelli** [comment]
>  The way version-guard is implementing it is not handy: the version check is not based on a unique fine grained source like engines content in package.json and it does not seem to be able to optionally only use it.

It has worked well for me for now and is a very simple implementation, which ensures it will work in old runtimes.

Doing a full on semantic versioning check would either require a naive parser of semver ranges or a dependency for parsing the semver ranges, and the dependency is likely to not have as wide support as `version-guard` needs.

> unneeded slower async primitives to read file replaced by faster sync implementation (for the sake of using primitives with a semantic matching CLI synchronous design)?

Any performance difference is negligible in this case, I would say that its a matter of taste where both are acceptable options.

I'm going to a bit harsh and close this. If we want to discuss performance improvements or compatibility improvements we are better of doing so in dedicated issues that focuses on a problem rather than on a solution.

Thanks for the PR though 👍

**Comment by jerome-benoit** [comment]
> > The way version-guard is implementing it is not handy: the version check is not based on a unique fine grained source like engines content in package.json and it does not seem to be able to optionally only use it.
> 
> It has worked well for me for now and is a very simple implementation, which ensures it will work in old runtimes.
> 
> Doing a full on semantic versioning check would either require a naive parser of semver ranges or a dependency for parsing the semver ranges, and the dependency is likely to not have as wide support as `version-guard` needs.
> 

Currently, neostandard is working with different JS runtime. If strict runtime version checking is introduced with version-guard:
-  it will make suddenly neostandard fails on other JS runtime than node
- version-guard can be replaced by a few lines of codes + one dependency to parse semantic version. With cross runtime support

Since tool for coding style is expected to be runtime agnostic, I think the project description should clearly state it as a design goal. 

> > unneeded slower async primitives to read file replaced by faster sync implementation (for the sake of using primitives with a semantic matching CLI synchronous design)?
> 
> Any performance difference is negligible in this case, I would say that its a matter of taste where both are acceptable options.
> 

Both works. And one is similar to using an anvil to nail :)

**Comment by voxpelli** [comment]
> Currently, neostandard is working with different JS runtime

As far as I know, ESLint is only supported on Node.js, and yes, this config even contains `eslint-plugin-n` so it’s definitely geared towards Node.hs

If one wants a runtime independent solution, then something like Biome (#77) would be a better approach

**Pull request closed without merging**
