### PR TITLE
feat!: add eslint-plugin-promise support

### LINKED ISSUE #14: Add `eslint-plugin-promise`
When it supports ESLint 9: https://github.com/eslint-community/eslint-plugin-promise/issues/449

### PR DESCRIPTION
**Pull request by jerome-benoit**
closes #14

### CODE REVIEW

**Comment by voxpelli** [comment]
Thanks 🙏

I mistakenly pushed another change directly to `main` rather than as a PR: https://github.com/neostandard/neostandard/commit/26b472b52b32d704f60f12bfb228692f2f74b2f6

Thoughts on that? Can we extend that change with this plugin as well?

**Comment by jerome-benoit** [comment]
> Thoughts on that? Can we extend that change with this plugin as well?

I will align the PR changes with export feature shortly after. And ping for review.

**Comment by voxpelli** [comment]
Updated title to reflect that this is a breaking change :)

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@voxpelli how would this be breaking?

**Comment by voxpelli** [comment]
@mcollina it adds linting rules, so it's as breaking as when we added back TS style linting

**Review by voxpelli — APPROVED** [review]

**Pull request merged**
