### PR TITLE
ci(dependents): add `sync-update` flow

### PR DESCRIPTION
**Pull request by voxpelli**
Adds a companion flow to the one in #121.

This workflow is not only refreshing the existing list of dependents but updating it in its entirety – also adding new dependents that may have emerged.

### CODE REVIEW

**Comment by jerome-benoit** [comment]
Can `sync-update` and `sync-refresh` generate conflicting PRs?

**Comment by voxpelli** [comment]
@jerome-benoit `sync-refresh` will always be a subset of the changes in `sync-update`, but yeah, their PR:s can probably conflict I guess, not sure if one could find some way to deal with that gracefully / automatically

**Comment by jerome-benoit** [comment]
> @jerome-benoit `sync-refresh` will always be a subset of the changes in `sync-update`, but yeah, their PR:s can probably conflict I guess, not sure if one could find some way to deal with that gracefully / automatically

One is scheduled at the end/begin of month, the other at the middle of month?

**Comment by voxpelli** [comment]
> One is scheduled at the end/begin of month, the other at the middle of month?

The intent with separating them has been that `sync-refresh` is more lightweight and less likely to be breaking, and thus can run more often, whereas the `sync-update` one is both more heavy to run (bombards ecosyste.ms servers with requests) and will be adding new projects in a way that the `sync-refresh` wont be

**Comment by jerome-benoit** [comment]
> The intent with separating them has been that `sync-refresh` is more lightweight and less likely to be breaking, and thus can run more often, whereas the `sync-update` one is both more heavy to run (bombards ecosystem servers with requests) and will be adding new projects in a way that the `sync-refresh` wont be

The later is run each monday. The former is run the 6th day of the month. To ensure the former will left a small merge window trying to avoid conflicts, it can be run on friday/... the first week of the month.

**Review by bcomnes — APPROVED** [review]

**Pull request merged**
