### PR TITLE
ci: add release-please and enforce conventional commits

### LINKED ISSUE #18: Set up automated releases

### PR DESCRIPTION
**Pull request by voxpelli**
To enable everyone of us to release, this PR sets up release-please and enforces conventional commit syntax.

The release-please setup uses a `npm` environment that's locked down to the `main` branch and which contains a `NPM_TOKEN` secret with a granular token that can only publish to the `neostandard` package (owned by my npm account at the moment)

The conventional commit enforcement happens in two ways:

* Through a `husky` `commit-msg` hook that runs my [`validate-conventional-commit`](https://github.com/voxpelli/validate-conventional-commit) module (much much smaller and simpler than eg `@commitlint/cli`)
* Through [`mtfoley/pr-compliance-action`](https://github.com/mtfoley/pr-compliance-action) that validates the title of PR:s and fails if it does not follow conventional commit

fixes #18

### CODE REVIEW

**Review by bcomnes — APPROVED** [review]
Not a fan of precommit hooks (they get in the way when doing git surgery) but willing to try this out.

**Comment by voxpelli** [comment]
> Not a fan of precommit hooks (they get in the way when doing git surgery) but willing to try this out.

I guess that if we force squash merges and enforces name of PR:s then we can skip it

**Comment by bcomnes** [comment]
Just land it as is, we can iterate later.

**Comment by voxpelli** [comment]
@bcomnes fixed it ;P

**Pull request merged**
